### ISSUE TITLE
Not compatible with Python 3.x

### ISSUE THREAD

**Issue by AngeloStavrow** [klm1/kiln-local-backup#10]
Due to breaking changes in 3.x, the script will fail with an "Invalid Syntax" error when calling

`print console_encode('Getting the list of repositories from %s' % server)`

Users are not explicitly warned against using this script with Python 3.x, which has caused some confusion.

**Comment by klm1** [comment]
That's a really good point, Angelo. In addition, I'll see about making the script work with Python 3 as well.
